### ISSUE TITLE
A3W_extDB_pack.zip contains outdated A3Wasteland_settings folder

### ISSUE THREAD

**Issue by contactgus** [A3Wasteland/Release_Files#10]
e.g. it contains the outdated bannedNames.sqf that causes the BIS_fnc_AAN script restriction

**Comment by contactgus** [comment]
note: A3W_savingMethod = "extDB"; has to be set in main_config.sqf if you decide to update it with the latest settings folder

**Comment by clontarfx** [comment]
Can confirm, the zips have not been updated.
