### ISSUE TITLE
Missions are not finishing

### ISSUE THREAD

**Issue by JA3S** [A3Wasteland/Release_Files#13]
Hello Agent,
I am using your new 1.3b and I found that the Vehicle missions don't finish after last Soldier is killed. It happened on Transport Helicopter, Light Armed Vehicle and Armed Helicopter mission. BTW Enemy Outpost worked fine.

I tested with my mission file and with A3W 1.3b vanilla file both act the same.
Thank you
Best Regards
Jaeger

**Comment by AgentRev** [comment]
already fixed, always update and retest before reporting bugs, I push fixes multiple times a day
