### ISSUE TITLE
script restriction after update

### ISSUE THREAD

**Issue by biabock** [A3Wasteland/Release_Files#14]
hey, after update my mission and filters to latest one i'm getting people being (like 5/day, not much, but...) kicked by:
```
#3 " click %1 %2",_this,time];


[_caller, _veh, _override] onMapSingleClick 
{
if (_alt) then 
{
[_this select 0, _this select 1, _"
```
what is this? someone got the same?

**Comment by AgentRev** [comment]
huh... looks like code from Epoch... lol...

https://github.com/Sandbird/Dayz.Epoch.3d.Editor.Live.Mission-with-Database/blob/4e0ea4c0309875a2fa1a9baac02af29181afcbf9/missions/3d.live.DayzEpochTemplate.Chernarus/dayz_code/system/functions/systems/fn_supplydropService.sqf#L50-L60

**Comment by biabock** [comment]
the only things that use 'onMapSingleClick' are admin functions (proving grounds and TP)
I didn't find nothing more that use it... This is weird

**Comment by AgentRev** [comment]
there is a long-standing problem with scripts.txt, sometimes the game somehow keeps code from other missions in the memory after switching servers, which can sometime get scanned. I think I will remove the file entirely, it's been causing too much trouble with very little actual hack detection.
