### ISSUE TITLE
How to remove enemies' points on the map

### ISSUE THREAD

**Issue by sanches1985** [A3Wasteland/Release_Files#15]
How don't let players see enemies on the map. At host server Wasteland. Does anybody know how to remove it?

**Comment by AgentRev** [comment]
http://forums.a3wasteland.com/index.php?topic=2601.0

**Comment by AgentRev** [comment]
You need to find the `xxx.Arma3Profile` file for your server to edit those values. Here is a guide on where you can find it: http://forums.a3wasteland.com/index.php?topic=595.msg3663#msg3663

**Comment by sanches1985** [comment]
thank you very much!
