### ISSUE TITLE
W8 on update

### ISSUE THREAD

**Issue by C74K** [A3Wasteland/Release_Files#21]
ARMA 3:Contact DLC update request

**Comment by AgentRev** [comment]
working on it

**Comment by C74K** [comment]
Good news XD

**Comment by AgentRev** [comment]
I didn't have time to implement the DLC before leaving on vacation. I planned to do it last weekend, but I had to do overtime at my job and it took all my available free time. I won't be able to work on Arma until Aug 7th, my apologies.

**Comment by JoSchaap** [comment]
Rev, you come first!

Take all the time you need. and then some.
You've been doing awesome work and I can't even imagine to ever catch up!

Take care of yourself. And all the time you need!

Jo.

Outlook voor Android downloaden

________________________________

**Comment by C74K** [comment]
> I didn't have time to implement the DLC before leaving on vacation. I planned to do it last weekend, but I had to do overtime at my job and it took all my available free time. I won't be able to work on Arma until Aug 7th, my apologies.

OK np.
